language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  app: trailtime
  api_key:
    secure: loo9U6c0t15G5cL+hBXkNzaldpQwyS1lotMEGuPJIBnry6v2Rj5lWSX8IJZVhxOjfMQoW6oA34KHLNs3x64+6Ux1c6iTwD00ORQxJA43y62mFEGELYdZl3+DIBqqTHKbF94sbQ2w7iaUG6Sfgu1JSj2i4jeXCJCsKp4ZNEW4LxcWbwI1MdTFHr86azXQqQslmg5L9Iu2t+jjGh/5V/wKIA/ssfDTPAC1SGiVdgB9vwDR8im/2spCatq3r0AuOouyN7aNsF/6STjTi6vF3q7Jnm9890TmcblNzwiV1PFMLqgYIwgu+2TXDQx5/srRTcB4r7wzPvoELcotntdjUKV2znuUtS1TBO6clrgsMtU2x3Jmvt151rVI+k31wvtQWrGDPayL9GBVbHf66VU+8JqNT+Ze++xas7jpR9I2mSZ0g+tDmD8gGz1pk7Wk0lou16RoraVzR0Ub0BShlU/xcJBwkqeT/68dwUBLx+nqhTYcKqMTo9DFkNj8FGAZqytYhUMKd+7OnQUP4Xe/x++nrhcQNcUUGxqhtZLiRqq3tbk0g2S3sfeApqzUBB2emBsiNB47w2QkIaMc9We2m41gtVXsu1lSjEfu/25M4zxRsVGC+c5JNSDO0H7nCtqtBZTpocV6IAftf+0J/baGuDOtegvX3//DtdBHKsCcuR80MIQd470=
